name: ENV variables
on: push
env:
  WF_ENV: Available to all jobs
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      WF_LOG_ENV: Available to jobs in log env
    steps:
      - name: Push a random files
        run:  |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          # echo $RANDOM >> random.txt
          # ls -a
          # git add -A
          # git commit -m "random file"
          # git push
      - name: Log ENV variables
        env:
          WF_STEP_ENV:  Available to only this step
        run:  |
          echo "WF_ENV: ${WF_ENV}"  
          echo "WF_LOG_ENV: ${WF_LOG_ENV}"
          echo "WF_STEP_ENV: ${WF_STEP_ENV}"
      - name: Log Env Step 2
        run:  |
          echo "WF_ENV: ${WF_ENV}"  
          echo "WF_LOG_ENV: ${WF_LOG_ENV}"
          echo "WF_STEP_ENV: ${WF_STEP_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default env variables
        run:  |
          echo "HOME: ${HOME}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "WF_ENV: ${WF_ENV}"  
          echo "WF_LOG_ENV: ${WF_LOG_ENV}"
          echo "WF_STEP_ENV: ${WF_STEP_ENV}"
