name: ENV variables
on: push
env:
  WF_ENV: Available to all jobs
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      WF_LOG_ENV: Available to jobs in log env
    steps:
      - name: Log ENV variables
        env:
          WF_STEP_ENV:  Available to only this step
        run:  |
          echo "WF_ENV: ${{EF_ENV}}"  
          echo "WF_LOG_ENV: ${{WF_LOG_ENV:}}"
          echo "WF_STEP_ENV: ${{WF_STEP_ENV:}}"
      - name: Log Env Step 2
        run:  |
          echo "WF_ENV: ${{EF_ENV}}"  
          echo "WF_LOG_ENV: ${{WF_LOG_ENV:}}"
          echo "WF_STEP_ENV: ${{WF_STEP_ENV:}}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default env variables
        run:  |
          echo "HOME: ${{HOME}}"
          echo "GITHUB_REPOSITORY: ${{GITHUB_REPOSITORY}}"
          echo "GITHUB_EVENT_NAME": ${{GITHUB_EVENT_NAME}}"
          echo "WF_ENV: ${{EF_ENV}}"  
          echo "WF_LOG_ENV: ${{WF_LOG_ENV}}"
          echo "WF_STEP_ENV: ${{WF_STEP_ENV}}"
