name: Share data workflow
on: [push]
jobs:
  upload-job:
    name: Save output
    runs-on:  ubuntu-latest
    steps:
      - shell: bash
        run:  |
          expr 1+1 > output.log
      - name:  Upload output file
        id: 'uploadfile'
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  download-job:
    name: Download Log
    runs-on:  ubuntu-latest
    needs:  ['upload-job']
    steps:  
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file